version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kanban-app
      POSTGRES_PASSWORD: test123
  code:
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - .:/code
    depends_on:
      - db
